#!/usr/bin/env ruby
require "net/http"
require "twitter"

Twitter.configure do |config|
  config.consumer_key = "a3NSIbHHJ2sHRW8esfP8KQ"
  config.consumer_secret = "jzUlgp05kpqu1Zhwr6de3p9MaS1kksibB1fP0rNY40"
  config.oauth_token = "1007933707-I4UQrvGhk7khDWQ5G1W3R6bOg0Bv3LV9ZJORmRr"
  config.oauth_token_secret = "jbptSPVE7nOwT2wfCRURti9eYBTzhJLCz8jpjOSvSg"
end

# puts Twitter.user("gem").inspect
# puts Twitter.user(213747670).inspect

# puts Twitter.status(27558893223).inspect

# puts Twitter.followers("gem").inspect
# puts Twitter.followers(213747670).inspect
# puts Twitter.followers.inspect

# puts Twitter.friends("gem").inspect
# puts Twitter.friends(213747670).inspect
# puts Twitter.friends.inspect

# puts Twitter.user_timeline("gem").inspect
# puts Twitter.user_timeline(213747670).inspect

# puts Twitter.home_timeline.inspect

# puts Twitter.mentions_timeline.inspect

# Twitter.search("to:justinbieber marry me", :count => 3, :result_type => "recent").results.map do |status|
#   puts "#{status.from_user}: #{status.text}"
# end
Twitter.search("to:wflabs2012", :result_type => "recent").results.map do |status|
  puts "#{status.from_user}: #{status.text}"
  uri = URI("http://localhost:3000/products.json")

  Net::HTTP.start(uri.host, uri.port) do |http|
    request = Net::HTTP::Get.new(uri.request_uri)
    response = http.request(request)
    json_response = JSON.parse(response.body)

    status.hashtags.each do |hashtag|
      puts "\n[HASHTAG] #{hashtag["text"].downcase}"

      json_response.each do |product|
        if hashtag["text"].downcase.match(/.*#{product["brand"].downcase.gsub(/\s/,"")}.*/)
          begin
            Twitter.update("@#{status.from_user} Check out a product from ##{hashtag["text"]} at #{product['url']}", :in_reply_to_status_id => status.id)
            puts "[RESPONSE] Replied"
          rescue Twitter::Error::Forbidden => e
            puts "[RESPONSE] Skipped - Already replied"
          rescue Twitter::Error => e
            puts "[ERROR] #{e}"
          end

          break
        end
      end
    end
  end

  puts "========"
end

# puts Twitter.search("#ruby -rt", :lang => "ja", :count => 1).results.first.text

# Twitter.update("I'm tweeting with @gem!")

# Twitter.follow("gem")
# Twitter.follow(213747670)